apiVersion: v1
kind: ConfigMap
metadata:
  name: userapi-config-map
  namespace: fgc
data:
  jwt_issuer: "fgcapi"
  jwt_audience: "fgcapi"
  jwt_token_ttl: "10"
  root_first_name: "FirstName"
  root_last_name: "LastName"
  root_email: "admin@fgc.com"
  rabbitmq_usercreated_exchange: "fgc"
  rabbitmq_usercreated_routingkey: "user.created"