apiVersion: v1
kind: Secret
metadata:
  name: userapi-constr-secret
  namespace: fgc
type: Opaque
stringData:
  connection-string: "Server=sqlserver-service;Database=FGC_User;User Id=sa;Password=rohPav-juKmeb-DIhku9!;TrustServerCertificate=True"