apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi-deployment
  namespace: fgc
  labels:
    app: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: fcg-userapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__Default
          valueFrom:
            secretKeyRef:
              name: userapi-constr-secret
              key: connection-string
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: jwt_issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: jwt_audience
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: userapi-jwt-key-secret
              key: key
        - name: Jwt__TokenTtlInMinutes
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: jwt_token_ttl
        - name: RootUser__FirstName
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: root_first_name
        - name: RootUser__LastName
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: root_last_name
        - name: RootUser__Email
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: root_email
        - name: RootUser__Password
          valueFrom:
            secretKeyRef:
              name: userapi-root-pwd-secret
              key: password
        - name: RabbitMQ__URI
          valueFrom:
            secretKeyRef:
              name: userapi-mq-uri-secret
              key: conn
        - name: RabbitMQ__UserCreatedEvent__Exchange
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: rabbitmq_usercreated_exchange
        - name: RabbitMQ__UserCreatedEvent__RoutingKey
          valueFrom:
            configMapKeyRef:
              name: userapi-config-map
              key: rabbitmq_usercreated_routingkey